getgauge/taiko

- lib/api.json
- lib/pageHandler.js
- lib/taiko.js
- lib/targetHandler.js
- Automatically switches control to new target opened
- Allows to switch between tabs using url or page title
Below scripts demos on accessing elements in newly opened page, switching tab and accessing elements there.
```
(async () => {
try {
await openBrowser();
await goto('https://gauge.org');
await click(link(toLeftOf('Plugins')));
await highlight(link("Features"));
await switchTo('Open Source Test Automation Framework | Gauge'); 
await click("Plugins");
} catch (e) {
console.error(e);
} finally {
closeBrowser();
}
})();
```
> Handle new target

- lib/helper.js
- lib/networkHandler.js
Now users can use intercept as following.
`intercept( "example.com",  { body: {  cart:['product1 details', 'product2 details' ] } } );`
> Extending intercept api to accept json as response body

- lib/taiko.js
Ignore all the elements which are merely a wrapper for the element matching the provided selector or text.
> Fix click api to click on the innermost element which matches the selector.

- lib/networkHandler.js
- lib/pageHandler.js
- lib/taiko.js
- No need to clear browser local storage as taiko always creates a unique [--user-data-dir](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/user_data_dir.md).
- Persist cookies and cache throughout a single run. It will help the user to share the session across tab.
> Browser local storage and cookies

- README.md
- docs/layout/partials/header.html
Fix the quotation mark. In case anyone who wants to copy command from the Webpage or README will execute the command failed.
> Fix the quotation mark

- bin/runFile.js
- bin/taiko.js
- lib/taiko.js
- lib/util.js
- package-lock.json
- package.json
```
Usage: taiko [options]
taiko <file> [options]
Options:
-v, --version                 output the version number
-o, --observe                 enables headful mode and runs script with 3000ms delay by default.
pass --wait-time option to override the default 3000ms
--slow-mod                    similar to --observe option
-w, --wait-time <time in ms>  runs script with provided delay
--emulate-device <device>     Allows to simulate device viewport. Visit https://github.com/getgauge/taiko/blob/master/lib/device.js for all the available devices
-h, --help                    output usage information
```
> Incorporate commander.js to handle taiko command line args and flags.

- lib/taiko.js
- package-lock.json
- test/functional-tests/specs/ElementsAPI.spec
- test/functional-tests/specs/ElementsAPIIFrame.spec
- test/functional-tests/specs/browserActions.spec
- test/functional-tests/specs/positionalSelectors.spec
- test/functional-tests/specs/positionalSelectorsIFrame.spec
- test/functional-tests/tests/click.js
- test/functional-tests/tests/htmlElementAPI.js
- test/unit-tests/radioButton.test.js
- test/unit-tests/test-util.js
- test/unit-tests/textMatch.test.js
#321
- get text nodes using xpath when searching texts in `match()`
- update `isHidden()` method to use parentElement for text nodes and use offsetHeight and offsetWidth instead of offsetParent
- update click verifying if element is covered to use range for finding position of text nodes
- modify proximity selector logic for left, right, top and bottom as they were fetching overlapping elements too
- fix functional tests
- add integration test for text match
should also fix #335 and #186
> #321 handle textnode

- bin/taiko.js
The --load option was not working due to the fact that the parameters used are incorrect. Updated parameters passed to runFile to match signature.
> Fixed incorrect parameters to runFile

- bin/taiko.js
- lib/plugins.js
- package.json
- test/unit-tests/plugins.test.js
**Taiko** plugins can extend **Taiko** via subcommands
`taiko <taiko-pluginname> <options>`
**Example:** 
[taiko-diagnostics](https://github.com/saikrishna321/taiko-diagnostics/) can extend Taiko via subcommands as `taiko diagnostics <options>`
In order to be able to extend Taiko via subcommands, plugins have to implement a few things.
- Add a **capability** section in **package.json**
{ 
...,
capability: ["subcommands"],
...
}
- Add `exec` API.
Taiko will invoke plugin's `exec` API with all the options passed to Taiko subcommand.
> Added support for plugins to extend taiko via subcommands

- README.md
- docs/layout/partials/header.html
- lib/repl.js
Single letter variables tend to be confusing and make the code less
readable. Let's use the full word `error` instead of `e` for clarity.
> Avoid single-letter variables in REPL output

- lib/taiko.js
Show warning when a proximity selector is used with `selectHiddenElement` option.
Show when Taiko default highlight on action tries to highlight a hidden element.
> Handling hidden elements

- test/unit-tests/closeTab.test.js
Fixes testing of close tab events similar to 9827ff331d81e71e4da01cb6fa0bbc15c82cf702 as mentioned in this comment https://github.com/getgauge/taiko/pull/759#pullrequestreview-278287282
> fix close tab tests to wait for events

- lib/repl/repl.js
> Provide more details in dot api

- lib/repl/repl.js
https://github.com/getgauge/taiko/issues/1016
Adds a `.trim()` to the `isTaikoFunc()`'s split token, so that if the user's style includes spaces between functions and the opening parenthesis, eg: `goto (foo)` (note the space), the lookup resulting from `.code` will still recognize Taiko functions as such and add `await`.
> Adds `trim()` to the REPL's `.code` function lookup

- lib/taiko.js
This fixes the display of documentation while running the
.api command in the REPL.
Without this fix the tableCell api is not added to api.json
while generating documentation.
> Use the right annotation for tableCell documentation

- lib/install.js
Can already be done via an env var but there is no convenient way to skip on every install.
It's useful in constrained environments where one needs to use a specific version of Chromium.
> Chromium download can be skipped when specified in .npmrc

- lib/taiko.js
I had an issue similar to [#140](https://github.com/getgauge/taiko/issues/140) wherein the screen size of browser that is opened was too small for the application that I am working on.
This [commit](https://github.com/getgauge/taiko/commit/ee4c6652f8323321c24138f103d4eb86339e72a4) supposedly fixed the issue but here the --window-size argument has a default set to --window-size=1440,900 without checking if there is any --window-size argument passed or not.
In the pull request I have added a check to see if the --window-size argument is passed or not before falling back to default '--window-size=1440,900' when openBrowser is called in headless mode.
> Added check for --window-size argument before adding default value for it when openBrowser is called in headless mode.

- lib/taiko.js
- test/unit-tests/switchTo.test.js
Raise an error with suggestion when an empty string is passed to the `switchTo` api.
```
> switchTo("")                                                                                                                               
✘ Error: Cannot switch to tab or window. Hint: The targetUrl is empty. Please use a valid string or regex, run `.trace` for more info.       
```
Fixes #1057
> Throw error when supplied targetUrl to switchTo is empty #1057

- lib/taiko.js
- test/functional-tests/specs/browserActions.spec
- test/unit-tests/switchTo.test.js
- since runtime domain is enabled in the runtimeHandler to listen for all executionContexts it need not be enabled again
Fixes #1063 
Fixes #939
> Remove duplicate runtime enable to fix switchTo

- lib/doActionAwaitingNavigation.js
- lib/taiko.js
- test/unit-tests/goto.test.js
- test/unit-tests/openTab.test.js
- since in cases like new tab open `loadEventFired` can be missed before taiko makes a new connection wait for page's readyState to be complete rather
> Fix waiting for loadEventFired

- lib/repl/awaitEval.js
- package-lock.json
- package.json
`babylon` was renamed to `@babel/parser` since 7.x
> Replace babylon with @babel/parser

- bin/taiko.js
- lib/taiko.js
- netlify.toml
Fixes https://github.com/getgauge/taiko/issues/1196
This set's up a netlify redirect
for a readable link to list of devices.
> Set up a redirect to list of devices

- lib/handlers/pageHandler.js
- lib/repl/repl.js
- lib/taiko.js
- package-lock.json
- package.json
- test/unit-tests/goto.test.js
- test/unit-tests/handlers/pageHandler.test.js
- types/taiko/index.d.ts
> #1203 return status code from goto

- types/taiko/index.d.ts
The [docs for waitFor](https://docs.taiko.dev/#waitfor) show an usage example with a boolean callback parameter, but the current type signature for the method doesn't support such a call. Calling `waitFor` passing a `() => Promise<boolean>` callback indeed works as depicted in the documentation.
This PR adds the missing type signature, plus some minor automatic linting fixes.
> Type signature for `waitFor` with boolean condition

- bin/taiko.js
- lib/handlers/pageHandler.js
- lib/taiko.js
- remove listeners on client before closing page and client to stop executing them while closing
- set clientproxy to null on closing browser which is returned by client() api
- catch error from closeBrowser on runner to avoid recursive action
Fixes #1241 
> #1241  Fix closeBrowser issues

- package.json
It makes type definitions to be correctly resolved by IDEs. Without, taiko has no discoverable typedefs.
See https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package for further explanation.
> Reference type declarations in package.json

- types/taiko/index.d.ts
Async functions have been missing correct `Promise<...>` return types.
> Fix incorrect async return types in type declaration

- README.md
- docs/FAQ.md
- docs/layout/partials/header.html
- lib/browserFetcher.js
- lib/browserLauncher.js
- lib/config.js
- lib/doActionAwaitingNavigation.js
- lib/handlers/domHandler.js
- lib/handlers/networkHandler.js
- lib/handlers/runtimeHandler.js
- lib/handlers/targetHandler.js
- lib/helper.js
- lib/taiko.js
- package.json
- test/unit-tests/browserLauncher.test.js
- test/unit-tests/config.test.js
- test/unit-tests/helper.test.js
- test/unit-tests/openBrowser.test.js
This PR tries to add basic support for firefox. 
- Download and install [firefox nightly](https://www.mozilla.org/en-US/firefox/all/#product-desktop-nightly) 
- Set `TAIKO_BROWSER_PATH` to firefox nightly's executable.
Example: `TAIKO_BROWSER_PATH="/Applications/Firefoxnightly.app/Contents/MacOS/firefox" taiko`
- Highlighting element on action is set to false as overlay domain is not supported
- openTab/closeTab does not work as expected since `New` is not available in firefox yet
- Autofocus on first input field does not happen
- file:// protocol does not emit events
- waitFoNavigation does not wait for network calls and frame loads
> Support for firefox

- lib/taiko.js
It looks like switchTo only works with Regex and window name object
and does not work with string. Which is ok. The regex will cover
almost all scenarios.
Updated the document to reflect that and also added more examples of
using it with a window identifier.
> Fix the switchTo documentation

- lib/eventBus.js
- lib/handlers/pageHandler.js
- lib/taiko.js
- lib/util.js
- types/taiko/index.d.ts
Fixes #1293
Refer https://github.com/getgauge/taiko/issues/1293#issuecomment-659858918
The HTML snippet to verify
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>
</head>
<body>
<h1>Foo</h1>
<h2>Bar</h1>
<h3>Baz</h1>
<button type="submit" onclick="prompt1()">String</button>
<button type="submit" onclick="prompt2()">Regex</button>
<button type="submit" onclick="prompt3()">Global</button>
<script>
function prompt1() {
value = prompt("Please enter your name", "Harry Potter");
document.querySelector("h1").innerText = value;
}
function prompt2() {
value = prompt("Please enter your name", "Harry Potter");
document.querySelector("h2").innerText = value;
}
function prompt3() { …
```
> Add regex and callback support for dialog handlers. #1293

- docs/integrating_with_test_runners.md
Jest integration example has `require` twice.
https://docs.taiko.dev/integrating_with_test_runners/#jest
> Fix Jest example

- lib/taiko.js
Following comments in #1028 setConfig `ignoreSSLErrors` is not documented. This PR changes this by aligning setConfig and getConfig API documentation.
> Harmonizing setConfig/getConfig api doc

- bin/taiko.js
- lib/browserFetcher.js
Fixes: #988
Packaging tools like web pack seems to strip non standard information from the `package.json` file. 
Taiko reads metadata from `package.json`, this PR adds a check to raise the right error when it 
cannot find browser version information.
> Check package.json before reading version

- README.md
Fixes #1339
Test it!
```
openBrowser()
goto("https://jsfiddle.net/0sgt8azo/")
```
Then use the example in README.md
> Fix XPath selector example

- lib/handlers/networkHandler.js
- lib/taiko.js
- test/unit-tests/handlers/networkHandler.test.js
- types/taiko/index.d.ts
We have a few cases where we want to customize what throughput/latency values we want to use. With this PR, we can either use the preset values already present in Taiko, or supply an object that fits Chrome Dev Tools' needs. Hopefully this is still within the spirit of the repository, let us know if there are any changes you'd like us to make!
> Extend emulateNetwork to accept custom objects

- lib/elements/dropDown.js
- lib/taiko.js
- test/unit-tests/dropDown.test.js
Fixes: #1111
```
await dropDown('Cars').select(/M.rc.d.s/);
```
Also fixes raised error on passing null values.
```
await dropDown('Cars').select(null)
Cannot destructure property \'stack\' of \'result.value\' as it is undefined.
```
```
await dropDown('Cars').select(null)
Option null not available in drop down
```
> Add regex support for dropdown text selection

- lib/elementSearch.js
- package-lock.json
- package.json
- test/unit-tests/click.test.js
- test/unit-tests/textMatch.test.js
fixes #1336 
- update text based search to not use xpath
- iterate through shadow dom to find matches
- remove matching types other than submit and reset
With this Taiko should have full shadow dom support.
TODO: If exact match is found in search further searches on shadow dom and iframes should also look for exact match only. Currently contains matches are also fetched from other subTrees.
> Update text search

- .gitignore
- lib/browserContext.js
- lib/elements/element.js
- lib/handlers/targetHandler.js
- lib/helper.js
- lib/taiko.js
- test/unit-tests/closeTab.test.js
- test/unit-tests/handlers/targetHandler.test.js
- test/unit-tests/incognito.test.js
- test/unit-tests/openTab.test.js
- test/unit-tests/switchTo.test.js
Fixes: #1062
Fixes: ##1440
* target handler handles both window and tab identifier caching
* Logic for registering tabs and windows with windows is not out of `BrowserContext`
```
openTab({ name: 'google'});
goto('google.com');
openTab('github.com', { name: 'github'});
openTab('taiko.dev')
switchTo({ name: 'github'});
switchTo(/google/);
closeTab({name: 'github'});
```
> Use identifiers for tabs

- .gitignore
- package.json
- test/types-test-support/generate-types-test.js
- types/taiko/index.d.ts
- types/taiko/test/taiko-types-test.ts
- types/taiko/tslint.json
Hi.
With this PR I would like to accomplish three things:
1. to have `dtslint` start analyzing the types
2. to introduce a test to check that all exported members of `taiko.js` are declared as types in `index.d.ts`
3. to add missing types and fix bug #1383 
The second point is achieved by automatically generating a typescript file that instantiates every member of `taiko.js` and giving it to `dtslint` for analyzing. Of course `dtslint` will complain for every member which is not declared in `index.d.ts`.
The first run gave errors on:
* clearHighlights
* timeField
* range
* tableCell
* color
All of them are fixed in this PR (which should also close bug #1383).
Please let me know what you think.
Thanks,
Filippo
> Adding missing types (and testing that we don't miss them again)

- package.json
- test/types-test-support/generate-types-test.js
- types/taiko/index.d.ts
The function `taiko.getConfig()` had no type declaration in `index.d.ts`
`GlobalConfigurationOptions` is a type that was declared incorrectly in `index.d.ts`, meaning that it was
not consistent with the default configuration as declared in
`lib/config.js --> defaultConfig`
I extended `generate-types-test.js`: now it generates a test that finds
inconsistencies between `GlobalConfigurationOptions` and `defaultConfig`.
> Fixed types for taiko.getConfig() and GlobalConfigurationOptions

- package-lock.json
- package.json
- types/taiko/index.d.ts
- types/taiko/test/taiko-types-test.ts
Hi!
With this PR I submit tests for all types related to taiko API's browser actions, i.e.:
- openBrowser
- closeBrowser
- client
- switchTo
- intercept
- emulateNetwork
- emulateDevice
- setViewPort
- openTab
- closeTab
- openIncognitoWindow
- closeIncognitoWindow
- overridePermissions
- clearPermissionOverrides
- setCookie
- deleteCookies
- getCookies
- setLocation
- clearIntercept
Some of them required to fix the type declaration in `index.d.ts`.
Also the last commit imports (as dev dependency) `devtools-protocol` which is the official repository of the protocol and provides some useful types that otherwise we should re-define. In this commit we use the type `Cookie` for `getCookies`. previously that was treated simply as an `object`, now it gets proper typing.
Sorry if the PR is quite …
> Test types for browser actions

- lib/taiko.js
- types/taiko/index.d.ts
- types/taiko/test/taiko-types-test-selectors.ts
Adding type test for selectors:
- $
- image
- link
- lstitem
- button
- filefield
- timefield
- range
- color
- tableCell
- textBox
- dropDown
- checkBox
- radioButton
- text
Some of the type declaration required fixings. Also documentation was subject to some fine-tuning.
Fixes issue #1465
> Type test for selectors

- lib/taiko.js
This address #660 We need to set protocol and target to get CRI connect to Selenoid cluster.
After the merge I shall add a taiko-selenoid plugin to get the integration work.
> Add protocol as options to openBrowser()

- lib/actions/dragAndDrop.js
- lib/handlers/runtimeHandler.js
- lib/taiko.js
- package-lock.json
- package.json
- there can be cases where element at point being outside the shadowdom in which case recursive piercing can go infinity
- bump up version to 1.0.23 for release
- hence pierce through each shadow root only once
Fixes #1476
> #1476 fix actions on shadowdom

- lib/taiko.js
There is a small typo in lib/taiko.js.
Should read `timeout` rather than `timout`.
> docs: Fix simple typo, timout -> timeout

- .eslintrc
- docs/api/api.njk
- lib/taiko.js
- test/docs-tests/gauge/specs/returnType.spec
- test/docs-tests/gauge/specs/returnTypeLinks.spec
- test/docs-tests/gauge/tests/click.ts
- test/docs-tests/gauge/tests/htmlElementAPI.ts
- test/docs-tests/jsdoc-inputs/returnTypes.js
This PR covers 2 things:
- fixing the links for standard types Array and Object (see issue #1567)
- changing return type from `Promise` to `Promise<void>`
> Improving return types in docs

- lib/handlers/fetchHandler.js
- test/unit-tests/intercept.test.js
Currently all registered intercepts with a non-zero count value gets their counts decremented for every call to `getMatchingInterceptor` regardless if the incoming request matches an intercept.
This bug causes intercepts with counts to not work as intended if there are other API calls made during a test. 
Signed-off-by: Marvin Khristian Zamora <mklzamora@gmail.com>
> Only decrement intercept.count when an intercept matches

- docs/record_and_run_tests.md
For people trying out Taiko, it might be useful to have instructions and a script that do not break when they observe it.
Signed-off-by: Guillaume Noireaux <gnoireaux@gmail.com>
> cookie consent breaks the script when not run headless

- package.json
- types/taiko/index.d.ts
This PR have dtslint run automatically before each push to git to verify the correctness of types and, primarily, check that other changes in the code are not breaking the type declarations.
This is related to issue #1571 
It also includes a fix for a misaligned type which would fail dtslint immediately 😉
> Add dtslint to husky

- lib/taiko.js
- test/unit-tests/waitFor.test.js
Fixes #1661. This updates the `waitFor` unit test to add some delay to be able to differentiate between `retryInterval` and `retryTimeout`, and a `beforeEach` that makes sure the page is loaded fresh upon each run.
> Pass proper retry interval/timeout to ElementWrapper.elements

- lib/actions/attach.js
- lib/actions/clear.js
- lib/actions/click.js
- lib/actions/focus.js
- lib/actions/highlight.js
- lib/actions/hover.js
- lib/actions/mouseAction.js
- lib/actions/pageActionChecks.js
- lib/actions/scrollTo.js
- lib/actions/write.js
- lib/elementSearch.js
- lib/elements/element.js
- lib/handlers/runtimeHandler.js
- lib/taiko.js
- package-lock.json
- package.json
- test/unit-tests/actions/pageActionChecks.test.js
- test/unit-tests/focus.test.js
- test/unit-tests/write.test.js
- pull out remaining page actions
- make all actions use `waitAndGetActionableElement` to ensure every action is performed on a stable element
- make isConnected check default for actions
> Clean up actions and wait for element to be connected before actions

- lib/actions/clear.js
- lib/actions/pageActionChecks.js
- lib/actions/write.js
- lib/elementSearch.js
- package-lock.json
- package.json
- modify write api to not pre fetch focused element
- make checking for actionable element on focused element if a selector is not given by user
> #1777 Check if foused element is actionable

- types/taiko/index.d.ts
`resizeWindow` API is merged 18 days ago #1793
But the type of this argument is not aligned with [the docs](https://docs.taiko.dev/api/resizewindow/) & [underlaying function](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setWindowBounds).
> Fix type of ResizeWindowOptions

- lib/browserLauncher.js
- lib/handlers/targetHandler.js
- test/unit-tests/handlers/targetHandler.test.js
- test/unit-tests/incognito.test.js
Fixes: #1822
This will enable CORS restrictions while testing site.
It's better to make this argument explicit to avoid potential
attacks on Taiko script that run on live sites.
Refer: 
The change is in `browserLauncher` however the other files changes were added by the linter.
> Enable web security by default

- docs/running_scripts_inside_the_browser.md
I add 'args' key to message variable because it didn't work. There was missing part.
> Fix evaluate passing data code snippet

- lib/config.js
This will allow us to read navigation and retry timeout values from environment variables and configurations. This will allow us to set defaults outside of our test setup
> fix(config): Allow navigation and retry timeout to be read from env

- types/taiko/index.d.ts
Implementing the following code as documented caused a compilation error in Typescript.
https://docs.taiko.dev/api/timefield/
```
await timeField('Birthday:').select(new Date('2020-09-20'))
```
Since line 23 of timeField.js raises an error for any type other than Date, we decided that only Date type arguments should be used for TimeFieldWrapper's select method.
https://github.com/getgauge/taiko/blob/master/lib/elements/timeField.js#L23-L25
Please point out if this fix is wrong.
> Fixed the argument type of TimeFieldWrapper's select method

- lib/proximityElementSearch.js
- package.json
Optimize proximity selector search by caching the calculated bounding rects of given proximity elements.
For Ex: 
```
$('.class-multiple-elements', toRightOf(text('Hello')))
```
`.class-multiple-elements',` returns 200 elements and `toRightOf` was calculated for ever element which impacted the performance.
> Cache proxomity element Rect

- lib/elementWrapper/elementWrapper.js
- package-lock.json
- test/unit-tests/data/visibility.html
- test/unit-tests/visibility.test.js
Current implementation always returns true for visibility check if the element is present in the DOM but not in viewport. As per the documentation API should only true when the element is in viewport. 
This PR fixes this issue. 
> fix isVisible check

- lib/browserLauncher.js
When launching chrome for the first time it opens
up an initialization dialog box that breaks the
openBrowser api
For more reference
https://github.com/getgauge/taiko/discussions/2061
> Do not pop up first run dialog on chrome

- package-lock.json
- package.json
- test/unit-tests/click.test.js
- test/unit-tests/tap.test.js
Tests on github action seem to fail while
asserting on the element as it might be
outside the viewport.
Also adding ts types to get rid of editor warning of missing types.
> Remove div height

- lib/actions/pageActionChecks.js
elem.contains(node) doesn't work when elem contains a shadow root.
> checkIfElementIsNotCovered shadowroot parent

- lib/actions/click.js
- lib/config.js
- test/unit-tests/config.test.js
Adds the ability to do click modifiers such as ctrl+click or alt+click from CDP dispatchMouseEvent:
https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchMouseEvent
> Fixes #2587 Adds the ability to use click modifiers

- lib/browserFetcher.js
@zabil quick review when you get a moment? I've tested this on my M1 MBP and `npm test` passes.
Also verified the binary image is indeed ARM64 (in case your machine is x86_64):
```console
$ file .local-chromium/mac_arm-1075999/chrome-mac/Chromium.app/Contents/MacOS/Chromium
.local-chromium/mac_arm-1075999/chrome-mac/Chromium.app/Contents/MacOS/Chromium: Mach-O 64-bit executable arm64
```
> Add support for Mac ARM64 Chromium

- package-lock.json
- package.json
Noteable:
- updates `documentation` packaget to 14.0.1 which fixes a critical vulnerability reported by `npm audit`
- updates to the latest devtools-protocol and chromium revision to match
This should remove all `npm audit` errors/warnings for downstream projects that depend on `taiko`.
cc: @zabil
> Update JS dependencies and Chromium

- docs/frequently_asked_questions.md
- test/types-test-support/generate-types-test.js
There are small typos in:
- docs/frequently_asked_questions.md
- test/types-test-support/generate-types-test.js
Fixes:
- Should read `instantaneous` rather than `instanteneous`.
- Should read `consistent` rather than `consinstent`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- package-lock.json
- package.json
Bumping to 1.3.8 + updating packages.
cc: @zabil
> Update JS packages and Chromium

- lib/taiko.js
- package.json
- types/taiko/index.d.ts
Fixes #2701 See this issue for more details on what this PR fixes. The options themselves do already work, they were just incorrectly documented and the TS type for these options was missing.
> Fix types and documentation for scrollTo() alignment options

- .github/workflows/release.yml
Hub is deprecated and no longer bundled with the ubuntu build images.
Refer https://mislav.net/2020/01/github-cli/
Use github cli https://cli.github.com/manual/gh_release_create
> Use github-cli instead of hub for releases

- README.md
- bin/taiko.js
- lib/repl/repl.js
Fix regression in version info display
Before
```
$ taiko
Version: 1.4.0 (Chromium: undefined)
Type .api for help and .exit to quit
```
After
```
$ taiko
Version: 1.4.0 (Chromium: 126.0.6468.0)
Type .api for help and .exit to quit
```
> Fix taiko version info display

- .github/workflows/taiko.yml
- lib/actions/pageActionChecks.js
- package-lock.json
- package.json
- scripts/updateChromium.ts
- test/docs-tests/gauge/package.json
- test/functional-tests/package-lock.json
- test/functional-tests/package.json
- test/functional-tests/specs/data/IFrameElements.html
- Bump gauge-ts plugin version
- Move windows builds to node 20
- Upgrade chrome version
Fixes #2732
> Upgrade gauge ts and chrome version

- lib/actions/click.js
- test/unit-tests/click.test.js
If a Relative Selector is passed in as the third argument inside of click(), it doesn't actually make it down to waitAndGetActionableElement. 
We found that `await click(element, options, within(withinElement))`  doesn't search in the "within" element with the Biome Migration changes
Signed-off-by: DCoomer <deshuncoomer@gmail.com>
> Update click.js for relative selectors

- .github/workflows/taiko.yml
- lib/taiko.js
- package-lock.json
- package.json
Fixes #2749
If we open a local browser after opening and closing a remote browser, the closeBrowser step hangs.
The `connectedToRemoteBrowser` property was not being reset after connecting to a remote browser.
> Set connectedToRemoteBrowser to false for non remote browser
