- lib/api.json
- lib/taiko.js
- Checks if document has a focused element before writing.
- Checks if element is writable before writing to it.
> Check if element is writable before write

- lib/api.json
- lib/taiko.js
- lib/targetHandler.js
- package.json
> Handling closeBrowser for headless mode and when the last tab is closed #157

- README.md
README edits
- use second person sentences/phrases
- capitalize proper nouns
> spellcheck and grammar edits

- docs/layout/assets/css/style.css
- docs/layout/assets/js/main.js
- docs/layout/page.html
- docs/layout/partials/toc.html
> bug fixes on landing page

- lib/browserFetcher.js
- lib/install.js
- lib/taiko.js
- SKIP_CHROMIUM_DOWNLOAD set to true to skip downloading chromium
- DOWNLOAD_HOST set to host url of mirror to download chromium
- EXECUTABLE_PATH set to launch browser from different location
> #246 handle chromium bundling

- lib/taiko.js
- Get the innermost element which contains text
- ignore if that element contains any other element without matching text
> Fix contains to get the innermost element

- docs/layout/page.html
> Updated GTM code to fix #265

- docs/layout/partials/header.html
- docs/layout/partials/toc.html
- Add details about .step command
- Add details about env variables
> #336 Update docs

- lib/taiko.js
1. Added a method to mimic clicking browser back button functionality.
2. Added a method to mimic clicking browser forward button functionality.
> Added page actions

- lib/taiko.js
** User can fetch various browser url attributes including:
** protocol
** path
** host
** search
** Full Url
> JD: Added browser URL attribute fetcher to support #351:

- azure-pipelines.yml
- package.json
- test/functional-tests/package.json
- test/functional-tests/tests/alert.js
- test/functional-tests/tests/assert.js
- test/functional-tests/tests/browserAction.js
- test/functional-tests/tests/checkBox.js
- test/functional-tests/tests/click.js
- test/functional-tests/tests/comboBox.js
- test/functional-tests/tests/htmlElementAPI.js
- test/functional-tests/tests/pageActions.js
- test/functional-tests/tests/selectors.js
- test/functional-tests/tests/write.js
Address #333 
All the functional test would point to root of taiko and not the released version, this helps to add tests for any new API.
https://dev.azure.com/saikrishna321/Taiko/_build/results?buildId=117
The failing test looks like know issues with taiko.
@sriv  @NivedhaSenthil
> Added support to run test on azure CI

- docs/layout/assets/js/main.js
Fix on issue with scroll when page is loaded.
> Scroll issue fix

- test/functional-tests/specs/browserActions.spec
- test/functional-tests/specs/pageActions.spec
- test/functional-tests/tests/browserAction.js
- test/functional-tests/tests/click.js
- test/functional-tests/tests/pageActions.js
> Adding missing tests

- lib/taiko.js
> fix #397 click on number

- lib/taiko.js
Update xpath to handle two cases
- implicte child of label
- label with id for
combine both xpath checks
> Finding elements by visible label 

- bin/taiko.js
Address https://github.com/saikrishna321/taiko-diagnostics/issues/13#issuecomment-474296651
@BugDiver Pls review
> load plugin from local or global node_modules

- lib/taiko.js
> #464 Handle using only proxmity selector

- README.md
Issue link : https://github.com/getgauge/taiko/issues/470
> Fix ReadMe example import error

- lib/taiko.js
- Make event handler available for plugins
- remove listeners properly
Fix for https://github.com/getgauge-contrib/taiko-screencast/issues/1
> Handle event emitter

- docs/layout/partials/toc.html
- docs/layout/partials/troubleshoot.html
Specifies the steps needed to be followed to use taiko on a raspberry pi running raspbian.
> Add raspberry pi trouble shooting section

- bin/runFile.js
- lib/helper.js
- lib/repl.js
- lib/taiko.js
- test/unit-tests/closeBrowser.test.js
- test/unit-tests/openBrowser.test.js
- Making runner's console log event based 
- Removed the wrapper for `exists` in REPL
- RunFile also uses the descriptions from emitted event.
- REPL now prints the return value along with the description.
> 483 Making runner's console log event based 

- lib/taiko.js
- test/unit-tests/click.test.js
Call scrollIntoViewIfNeeded on the parent element for text node.
> Fix for auto scroll 

- bin/taiko.js
- package-lock.json
> print hash in --version

- lib/taiko.js
- test/unit-tests/focus.test.js
It also searches for the first focusable element in the page, if the first element is not focusable
> update focus to throw error on unfocusable element #620

- lib/taiko.js
> handled click count to click specified number of times #658

- package.json
Run unit test as a pre-push hook to make sure things work before CI gets unhappy 😒
> added pre-push hook

- test/unit-tests/write.test.js
Adding an extra test based on the issue #740 and https://github.com/getgauge/taiko/commit/93c82f16f008c7a24f1060c9eb4a00e3a7cb97a8
> add issue 740 as test

- test/unit-tests/dropDown.test.js
this adds tests for issues like https://github.com/getgauge/taiko/issues/726
> add tests for dropdown logs

- docs/layout/partials/troubleshoot.html
> Update the docs - Taiko in Docker

- lib/handlers/networkHandler.js
- lib/taiko.js
Added request URL to the event logs.
Added extra logs to indicate that Taiko is waiting for a request.
```
<time-stamp> taiko:event Request started: 1000034115.2
<time-stamp> taiko:event Request started: 1000034115.3
<time-stamp> taiko:event Request resolved: 1000034115.3
<time-stamp> taiko:event Request resolved: 1000034115.2
```
```
<time-stamp> taiko:event Request started:     RequestId : 1000034115.2    Request Url : https://example.com/users.json
<time-stamp> taiko:event Request started:    RequestId : 1000034115.3    Request Url : https://example.com/styles/index.css
<time-stamp> taiko:event Waiting for:     RequestId : 1000034115.2    Request Url : https://example.com/users.json
<time-stamp> taiko:event Request resolved:	 RequestId : 1000034115.2
<time-stamp> taiko:event Request …
```
> Request life cycle logs

- lib/elementSearch.js
- lib/handlers/networkHandler.js
- lib/handlers/pageHandler.js
- lib/handlers/targetHandler.js
- lib/helper.js
- lib/repl/repl.js
- lib/taiko.js
- lib/util.js
- package.json
- test/functional-tests/server.js
- test/functional-tests/tests/assert.js
- test/functional-tests/tests/browserAction.js
- test/functional-tests/tests/htmlElementAPI.js
- test/functional-tests/tests/pageActions.js
- test/unit-tests/button.test.js
- test/unit-tests/checkbox.test.js
- test/unit-tests/closeTab.test.js
- test/unit-tests/evaluate.test.js
- test/unit-tests/highlight.test.js
- test/unit-tests/openBrowser.test.js
- test/unit-tests/radioButton.test.js
- test/unit-tests/screenshot.test.js
- test/unit-tests/test-util.js
- test/unit-tests/textMatch.test.js
- test/unit-tests/util.test.js
The current master lint-staged pre-commit hook was mapped incorrectly and was failing to look for any staged files on linting. Fixed it now.
This PR address that issue, Any changes to the staged files pre-commit hook runs `npm run lint`
Please squash and merge 🦊
> Fix linting

- lib/taiko.js
- test/unit-tests/openBrowser.test.js
@nehashri I have used the chromeProcess to check whether the browser is already open, please review the code and let me know if there are any changes
> Throw error if openBrowser is called multiple times #818

- .github/workflows/taiko.yml
- lib/handlers/pageHandler.js
- lib/helper.js
- lib/taiko.js
- lib/util.js
- package.json
- test/functional-tests/package-lock.json
- test/functional-tests/server.js
- test/functional-tests/tests/htmlElementAPI.js
- test/unit-tests/$.test.js
- test/unit-tests/button.test.js
- test/unit-tests/checkbox.test.js
- test/unit-tests/clear.test.js
- test/unit-tests/click.test.js
- test/unit-tests/dropDown.test.js
- test/unit-tests/filefield.test.js
- test/unit-tests/focus.test.js
- test/unit-tests/handlers/networkHandler.test.js
- test/unit-tests/highlight.test.js
- test/unit-tests/image.test.js
- test/unit-tests/link.test.js
- test/unit-tests/openBrowser.test.js
- test/unit-tests/radioButton.test.js
- test/unit-tests/screenshot.test.js
- test/unit-tests/test-util.js
- test/unit-tests/textBox.test.js
- test/unit-tests/textMatch.test.js
- test/unit-tests/write.test.js
- fixes unit tests for windows.
> Refactoring github actions workflow for tests.

- lib/taiko.js
- test/unit-tests/click.test.js
fix for issue #782: wrong user message for disabled element
> Bug: wrong user message for disabled element

- lib/taiko.js
- test/unit-tests/radioButton.test.js
**What this PR does**
1. Part of #811 
2. Follows same approach as #899
> Add support to find hidden element for RadioButton

- docs/layout/partials/header.html
- package-lock.json
Modify instructions to install gauge globally
> Install gauge globally

- test/unit-tests/$.test.js
- test/unit-tests/button.test.js
- test/unit-tests/checkbox.test.js
- test/unit-tests/dropDown.test.js
- test/unit-tests/focus.test.js
- test/unit-tests/image.test.js
- test/unit-tests/link.test.js
- test/unit-tests/listItem.test.js
- test/unit-tests/radioButton.test.js
- test/unit-tests/textBox.test.js
fix tests that do not await a promise
> Win flaky timeout

- lib/taiko.js
> handle race condition were client holding inactive target

- lib/elementWrapperUtils.js
- test/functional-tests/tests/write.js
- test/unit-tests/goBack.test.js
> fix eslint

- lib/taiko.js
- test/unit-tests/tablecell.test.js
- Added tableCell API. (#466)
- Added unit tests for the same.
> Added TableCell Support (#466)

- README.md
corrected click(checkbox(near("Username"))) to click(checkBox(near("Username")))
> Correct typo in Readme

- lib/taiko.js
https://github.com/getgauge/taiko/issues/1000
Adds documentation to `.exists` functions detailing what each parameter is
> .exists() documentation

- lib/taiko.js
https://github.com/getgauge/taiko/issues/1024
Makes documentation show actual default value
> Corrected the `retryInterval` documentation

- lib/elementSearch.js
- lib/elementWrapperUtils.js
- test/unit-tests/button.test.js
- test/unit-tests/isDisabled.test.js
Address #784 and Tested added for button API
> added isDisabled API on element

- lib/elements/elementHelper.js
- package.json
- test/unit-tests/elements/elementHelper.test.js
> Highlight only visible element.

- docs/layout/partials/header.html
> Fix broken link

- lib/config.js
- lib/taiko.js
- package.json
- test/unit-tests/config.test.js
> Code style check

- lib/handlers/inputHandler.js
- lib/taiko.js
- test/unit-tests/write.test.js
Fixes #1091  #1061 
Co-authored-by: SrinivasanTarget <srinivasan.sekar1990@gmail.com>
> added support to input emoji

- .github/workflows/taiko.yml
- examples/02-file_download.js
- lib/elementWrapper/elementWrapper.js
- lib/taiko.js
- test/functional-tests/specs/browserActions.spec
- test/unit-tests/$.test.js
- test/unit-tests/link.test.js
- test/unit-tests/write.test.js
Fixes https://github.com/getgauge/taiko/issues/1095
@zabil Can you please review
@msx752
> #1095 add support to find element by index

- lib/elementWrapper/elementWrapper.js
- test/unit-tests/textMatch.test.js
> exists to honour custom wait time

- lib/elements/element.js
- test/unit-tests/textMatch.test.js
> #1066 fix text() to return text value

- FAQ.md
- docs/FAQ.md
- docs/layout/partials/toc.html
Add a new FAQ page for Taiko and link to it on the Table of contents
> Add a new FAQ page

- lib/handlers/networkHandler.js
- lib/taiko.js
- test/unit-tests/goto.test.js
- test/unit-tests/handlers/networkHandler.test.js
> Configure http headers for a host when not present.

- lib/elementSearch.js
- lib/taiko.js
- test/unit-tests/checkbox.test.js
- test/unit-tests/radioButton.test.js
- test/unit-tests/textBox.test.js
Guys, I will appreciate your feedback.
Ps. Some indentations were made by git-hook/lint (checkbox.test.js)
> #1134 Case insensitive selectors

- lib/taiko.js
Fixes https://github.com/getgauge/taiko/issues/766
> Add options doc string for text API

- lib/handlers/pageHandler.js
- lib/taiko.js
- test/unit-tests/beforeunload.test.js
> Fix beforeunload API

- lib/taiko.js
- test/unit-tests/browserContext.test.js
- test/unit-tests/closeTab.test.js
- test/unit-tests/openBrowser.test.js
> Fix close browser

- package-lock.json
- package.json
This is the fix of `npm audit fix` command
> Fix npm audit report

- lib/handlers/domHandler.js
- package.json
- test/unit-tests/screenshot.test.js
> fix element screenshot with proximity selectors

- lib/handlers/pageHandler.js
- test/unit-tests/screenshot.test.js
- test/unit-tests/test-util.js
> fix screenshot for specific element with index

- lib/taiko.js
Fixes https://github.com/getgauge/taiko/issues/1198
Add documentation for
* openIncognitoWindow
* closeIncognitoWindow
> Add missing documentation links

- lib/elementSearch.js
- lib/elementWrapper/elementWrapperFactory.js
- lib/taiko.js
- test/unit-tests/$.test.js
- test/unit-tests/button.test.js
- test/unit-tests/checkbox.test.js
- test/unit-tests/dropDown.test.js
- test/unit-tests/filefield.test.js
- test/unit-tests/image.test.js
- test/unit-tests/link.test.js
- test/unit-tests/listItem.test.js
- test/unit-tests/radioButton.test.js
- test/unit-tests/textBox.test.js
- test/unit-tests/textMatch.test.js
- types/taiko/index.d.ts
> Select hidden elements

- docs/layout/partials/header.html
- lib/taiko.js
- test/unit-tests/openBrowser.test.js
> #164 allow setting browser args from env var

- lib/elementSearch.js
- test/unit-tests/browserContext.test.js
- test/unit-tests/textMatch.test.js
> Fix textsearch

- lib/taiko.js
- test/unit-tests/beforeunload.test.js
- test/unit-tests/clear.test.js
- test/unit-tests/textBox.test.js
- test/unit-tests/write.test.js
> #1236 cleanup write api

- lib/browserContext.js
- lib/handlers/browserHandler.js
- lib/taiko.js
- package-lock.json
- package.json
- test/functional-tests/tests/assert.ts
- test/functional-tests/tests/hooks.ts
- test/unit-tests/handlers/browserHandler.test.js
- test/unit-tests/incognito.test.js
- types/taiko/index.d.ts
> #1235 make url optional for openIncognitoWindow

- lib/taiko.js
- test/unit-tests/openBrowser.test.js
> Fixed an issue with browser args configured by TAIKO_BROWSER_ARGS env

- lib/elementSearch.js
- lib/handlers/runtimeHandler.js
- lib/taiko.js
- package-lock.json
- package.json
- test/unit-tests/beforeunload.test.js
- remove reconnect on closeBrowser
- use default config for beforeunload promises
- cache functions in browser during first call in every execution context
> #1236 Performance tweaks

- lib/taiko.js
> Fix write API documentation

- lib/handlers/pageHandler.js
- lib/repl/awaitEval.js
- lib/repl/repl.js
- test/unit-tests/handlers/pageHandler.test.js
> hide value for taiko commands in repl

- lib/taiko.js
> Add window name parameter to the documentation

- lib/handlers/networkHandler.js
- lib/handlers/pageHandler.js
- lib/handlers/runtimeHandler.js
- lib/handlers/targetHandler.js
- lib/taiko.js
> wait for listeners to be attached to complete connection

- types/taiko/index.d.ts
> Fix links to new documentation

- lib/repl/repl.js
> make global types available in repl #1349

- lib/repl/repl.js
> Showing browser path as part of version in REPL #1355

- .github/workflows/taiko.yml
- lib/actions/dragAndDrop.js
- lib/actions/pageActionChecks.js
- lib/actions/scrollTo.js
- lib/elementWrapper/elementWrapper.js
- lib/elements/element.js
- lib/handlers/inputHandler.js
- lib/taiko.js
- test/unit-tests/actions/pageActionChecks.test.js
- test/unit-tests/elements/element.test.js
> #279 Drag and drop support for html5 draggable elements

- lib/elementWrapper/elementWrapper.js
#1363
Update 'exists' function in elementWrapper.js to return 'Does not exist'
> Replace 'exists' return value to 'Does not exist'

- lib/doActionAwaitingNavigation.js
- lib/elementWrapper/buttonWrapper.js
- lib/helper.js
- lib/taiko.js
- fix memory leak caused by timeouts
> #1373 clean up timeout

- lib/handlers/fetchHandler.js
- lib/taiko.js
- package-lock.json
- package.json
- test/functional-tests/specs/pageActions.spec
- test/functional-tests/tests/htmlElementAPI.ts
- test/unit-tests/handlers/fetchHandler.test.js
- types/taiko/index.d.ts
> #1359 fix extra headers

- lib/elementWrapper/elementWrapper.js
- lib/elementWrapper/helper.js
- lib/taiko.js
- test/unit-tests/$.test.js
- test/unit-tests/button.test.js
- test/unit-tests/checkbox.test.js
- test/unit-tests/color.test.js
- test/unit-tests/dropDown.test.js
- test/unit-tests/filefield.test.js
- test/unit-tests/image.test.js
- test/unit-tests/link.test.js
- test/unit-tests/listItem.test.js
- test/unit-tests/radioButton.test.js
- test/unit-tests/range.test.js
- test/unit-tests/tablecell.test.js
- test/unit-tests/textBox.test.js
- test/unit-tests/textMatch.test.js
- test/unit-tests/timeField.test.js
> Provided a better error message when ElementWrapper is passed to a Selector function

- docs/index.html
- docs/running_scripts_inside_the_browser.md
Add section on the home page for tutorial on use cases for the evaluate API
> Add evaluate API tutorial

- README.md
> Refer to Taiko documentation and API from README

- lib/taiko.js
> Remove display of return value from evaluate

- lib/taiko.js
> Link to the right documentation

- lib/elementWrapper/helper.js
- test/unit-tests/button.test.js
> #1388 fix class to match mutiple selection

- lib/browserLauncher.js
- lib/config.js
- lib/taiko.js
- test/unit-tests/config.test.js
- test/unit-tests/test-util.js
> Ignore custom ssl certificates and disable cors security

- lib/taiko.js
- test/unit-tests/filefield.test.js
- test/unit-tests/image.test.js
- test/unit-tests/link.test.js
- test/unit-tests/tablecell.test.js
- test/unit-tests/textBox.test.js
- test/unit-tests/timeField.test.js
- test/unit-tests/write.test.js
> Do not capitalize the proximity selector messages

- lib/elementWrapper/elementWrapper.js
- lib/taiko.js
- test/unit-tests/$.test.js
- test/unit-tests/button.test.js
- test/unit-tests/checkbox.test.js
- test/unit-tests/color.test.js
- test/unit-tests/dropDown.test.js
- test/unit-tests/filefield.test.js
- test/unit-tests/image.test.js
- test/unit-tests/link.test.js
- test/unit-tests/listItem.test.js
- test/unit-tests/radioButton.test.js
- test/unit-tests/range.test.js
- test/unit-tests/tablecell.test.js
- test/unit-tests/textBox.test.js
- test/unit-tests/textMatch.test.js
- test/unit-tests/timeField.test.js
- types/taiko/index.d.ts
> Remove element wrapper list

- bin/runFile.js
- bin/taiko.js
- docs/configuring_taiko.md
- lib/eventBus.js
- lib/repl/repl.js
> Print action output when env is set. #1328

- lib/handlers/targetHandler.js
- lib/taiko.js
- package-lock.json
- package.json
- test/unit-tests/closeTab.test.js
> #1285 close and reconnect only if target matches active tab

- lib/handlers/runtimeHandler.js
> #1370 Clear up context id and catch on getProperties

- package-lock.json
- package.json
- types/taiko/index.d.ts
- types/taiko/tsconfig.json
Ciao,
As discussed in issue #1383 there are a few inconsistencies in the "types" definition `index.d.ts`.
This PR simply removes from `index.d.ts` two functions (`intervalSec` and `timeoutSecs`) which were removed from `taiko.js` some months ago, but the corresponding type declaration has stayed untouched.
This is a very small PR just to get me started working on the topic.
Since this is my first PR I am new to this workflow, I am making this very small PR in order to check if everything is fine in the process. If everything's fine I'll propose some more beefy PR to address other types' inconsistencies and I will also try and introduce some testing for the types.
Thanks,
Filippo
> Removed obsolete function defs

- lib/elementSearch.js
- lib/handlers/runtimeHandler.js
- test/unit-tests/textMatch.test.js
> Fix text regression

- lib/taiko.js
- test/unit-tests/tap.test.js
> #1437 fix check in tap

- package.json
Signed-off-by: sriv <srikanth.ddit@gmail.com>
> bump version -> 1.0.20

- lib/util.js
- package-lock.json
- package.json
> #1467 Fix repl

- docs/plugins.md
> added taiko-screeny plugin to doc

- README.md
- docs/overview.md
No idea what the last diff in line 182 is about. No intentional changes made there by me.
> Docs typo fixes. Closes getgauge/taiko#1483

- lib/taiko.js
> fix-1356 Add option to set wsDebugUrl to openBrowser API

- lib/elementSearch.js
- test/unit-tests/textMatch.test.js
- all buttons have type as submit and type or value of buttons are not rendered on screen hence dont assert them
- fix the wrong test
> #1476 fix buttons

- lib/handlers/runtimeHandler.js
> #1477 Fix assertion on runtime result

- docs/configuring_taiko.md
> Add missing documentation

- lib/taiko.js
> #1503 fix closeBrowser for remote browser

- lib/handlers/fetchHandler.js
- test/functional-tests/specs/intercept.spec
- test/functional-tests/tests/htmlElementAPI.ts
> #1520 fix request post data mocking

- lib/taiko.js
- test/unit-tests/proximitySelectors/within.test.js
> #1511 add withinn proximity selector

- README.md
- lib/elements/checkBox.js
- lib/elements/radioButton.js
- package-lock.json
- package.json
- test/unit-tests/checkbox.test.js
- test/unit-tests/radioButton.test.js
- types/taiko/index.d.ts
- types/taiko/test/taiko-types-test.ts
> #1499 bubble events for checkBox and radioButton API

- types/taiko/index.d.ts
> Adding type declaration for within()

- lib/elementSearch.js
- test/unit-tests/textMatch.test.js
> Fix text search for special char

- docs/taiko_in_docker.md
> Update docker related documentation

- lib/elementWrapper/dollarWrapper.js
- lib/handlers/runtimeHandler.js
- lib/taiko.js
- test/unit-tests/$.test.js
- types/taiko/index.d.ts
> #1557 Update $ selector to take a callback

- lib/actions/scrollTo.js
- package-lock.json
- package.json
- update scroll to element to use nearest for inline and block so that element stays put if it is in view
Fix #1565
> Update scroll to nearest

- lib/handlers/domHandler.js
Signed-off-by: jfgreffier <jf.greffier@gmail.com>
> Fix: positional difference

- docs/writing_plugins.md
Changes the wiki/Taiko-Plugin screencast Example 
Issue #789
> #789 change in wiki/Taiko-Plugin screencast Example

- lib/handlers/fetchHandler.js
- test/unit-tests/intercept.test.js
> Handling empty body in mock response #1596

- lib/taiko.js
> #1604 Warn on closeBrowser instead of erroring

- lib/taiko.js
https://bugs.chromium.org/p/chromium/issues/detail?id=1147809
> #1604 dont close page on windows headful mode

- docs/plugins.md
Add section to show how to load plugin before running Gauge specs
> Add plugin documentation

- lib/taiko.js
Adds omitDescription option in evaluate
Fixes #806
> Change lib/taiko adds omitDescription option in evaluate

- package-lock.json
- package.json
> Upgrade npm packages

- docs/writing_plugins.md
- lib/config.js
- lib/handlers/targetHandler.js
- lib/plugins.js
- lib/taiko.js
- package-lock.json
- package.json
- test/unit-tests/closeTab.test.js
- test/unit-tests/config.test.js
- test/unit-tests/handlers/targetHandler.test.js
- test/unit-tests/plugins.test.js
- Refactor cri.List usage 
- provide an option for plugins to register hooks that Taiko allows
- add docs for hooks
> Selenoid support

- .github/workflows/release.yml
> remove hub actions

- lib/taiko.js
- test/unit-tests/goto.test.js
- types/taiko/index.d.ts
Fixes: #1720
Also addes type that was missing in https://github.com/getgauge/taiko/commit/854119b764f1494966af425d8d591462b5d3b7c0
> Do not modify the protocol if mentioned in goto

- lib/handlers/pageHandler.js
- test/unit-tests/elements/elementHelper.test.js
- test/unit-tests/handlers/pageHandler.test.js
- cleanup test to properly remove listeners
- cleanup overwritting console from tests
> #1643 taiko should error when alert has no handler

- README.md
- docs/CONTRIBUTING.md
- docs/getting_help.md
> Move to Github discussions

- lib/connection.js
- lib/handlers/domHandler.js
- lib/handlers/networkHandler.js
- lib/handlers/pageHandler.js
- lib/taiko.js
- test/unit-tests/closeTab.test.js
- test/unit-tests/cookies.test.js
- test/unit-tests/goBack.test.js
- test/unit-tests/openTab.test.js
- pull out connection logic
- move domain logic to respective handlers
> Cleanup connections

- lib/handlers/fetchHandler.js
- package-lock.json
- package.json
- test/functional-tests/specs/intercept.spec
- test/functional-tests/tests/htmlElementAPI.ts
- types/taiko/index.d.ts
> #1769 Allow continue to not accept object

- .github/workflows/taiko.yml
> Update node version10 12, 14

- lib/handlers/targetHandler.js
- test/functional-tests/specs/browserActions.spec
- test/functional-tests/tests/browserAction.ts
- types/taiko/index.d.ts
> #1998 assign current target for openTab with blank url

- lib/actions/click.js
- lib/handlers/domHandler.js
- lib/taiko.js
- package-lock.json
- test/unit-tests/handlers/domHandler.test.js
- types/taiko/index.d.ts
This PR opens opportunity to perform click on given element at a certain position. 
Added Positions: left, right, topRight, topLeft, bottomRight, bottomLeft
```
click($('#action-canvas'), {position: 'right'})
click($('#action-canvas'), {position: 'left'})
click($('#action-canvas'), {position: 'bottomRight'})
click($('#action-canvas'), {position: 'bottomLeft'})
click($('#action-canvas'), {position: 'topRight'})
click($('#action-canvas'), {position: 'topLeft'})
```
@NivedhaSenthil @zabil Creating this PR for early feedbacks.
> Perform click on given positions

- lib/elementSearch.js
- lib/handlers/domHandler.js
- test/unit-tests/textMatch.test.js
Detailed explanation [here](https://github.com/getgauge/taiko/issues/2028).
> Text match should work on collapsed consecutive whitespaces

- bin/taiko.js
TAIKO_DISABLE_LOGOUT is not used anymore.
> Option --no-log not working

- lib/handlers/pageHandler.js
- test/functional-tests/specs/alert.spec
- test/functional-tests/specs/data/HTMLElements.html
- test/functional-tests/tests/alert.ts
> #1989 Fix prompt regression

- test/unit-tests/handlers/browserHandler.test.js
- test/unit-tests/handlers/domHandler.test.js
- test/unit-tests/handlers/emulationHandler.test.js
- test/unit-tests/handlers/fetchHandler.test.js
- test/unit-tests/handlers/inputHandler.test.js
- test/unit-tests/handlers/networkHandler.test.js
- test/unit-tests/handlers/pageHandler.test.js
- test/unit-tests/handlers/targetHandler.test.js
> Fix max listener reached warning in unit tests

- lib/elements/checkBox.js
- lib/elements/element.js
- lib/elements/elementHelper.js
- lib/elements/radioButton.js
- lib/elements/range.js
- test/functional-tests/specs/ElementsAPI.spec
- test/functional-tests/specs/ElementsAPIIFrame.spec
- test/functional-tests/specs/browserActions.spec
- test/functional-tests/specs/data/HTMLElements.html
- test/functional-tests/tests/htmlElementAPI.ts
- test/unit-tests/elements/checkBox.test.js
- test/unit-tests/elements/radioButton.test.js
- Fixes: #2173  
- for `radioButton` and `checkBox` in react app
- setting native checked value causes events to be raised correctly by react
Signed-off-by: atulv <atulverma82@gmail.com>
> Bug(checkbox|radio): Set checked value on native element setter so that events are triggered properly

- lib/data/devices.js
Signed-off-by: Haris Dzogovic <haris@dzogovic.de>
> Add new devices for mobile emulation

- lib/config.js
- lib/elements/elementHelper.js
- lib/taiko.js
- test/unit-tests/config.test.js
- test/unit-tests/elements/elementHelper.test.js
- test/unit-tests/test-util.js
- types/taiko/index.d.ts
- types/taiko/test/helpers.ts
Breaking change: can't use string highlightOnAction anymore. Instead use boolean.
> Boolean highlightOnAction

- lib/config.js
- lib/connection.js
- package-lock.json
> consider wsDebugUrl on open browser session

- types/taiko/index.d.ts
> Add count paramater type to intercept

- lib/taiko.js
- test/unit-tests/openTab.test.js
Issue : https://github.com/getgauge/taiko/issues/2644
Issue: https://github.com/getgauge/taiko/issues/1720
Fixed openTab navigation to non http protocol
> Arunkumar P: Fix openTab navigation to non http url

- package-lock.json
- package.json
Can we do a release to make the macOS arm64 enhancement available?
cc: @zabil
cc: @NivedhaSenthil
> Bump version 1.3.6

- package-lock.json
- package.json
@zabil here you go -- don't forget the label ;).
> Bump version 1.3.7

- .github/workflows/taiko.yml
- docs/_includes/styles.css
- package-lock.json
- package.json
Upgrade chromium version and bump up revision for a release
> Upgrade chromium to 133
